apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdep
spec:
  selector:
    matchLabels:
      dep: first
  replicas: 5
  template:
    metadata:
      name: deppod
      labels:
        dep: first
    spec:
      containers:
      - name: firstone
        image: tutum/apache-php
        ports:
        - containerPort: 80
