apiVersion: v1
kind: Pod
metadata:
  name: emppod
  labels:
    type: emp    
spec:
  containers:
  - name: p1
    image: centos:6
    env:
    - name: var1
      value: value1
    command: ['/bin/sh','-c','while true;do X=$[$X+1];echo "<center><h1>$X</h1></center>" > /usr/share/nginx/html/index.html;sleep 1;done']
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html
  - name: p2
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: myvol
    emptyDir: {}
--- 
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: empservice
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      targetPort: 80
  selector:
    type: emp
  type: LoadBalancer
