apiVersion: v1
kind: Pod
metadata: 
  namespace: demo
  name: twopods
spec:
  containers:
  - name: c1
    image: centos:6
    command: ['/bin/sh','-c','while true;do echo hello;sleep 1;done']
    env:
    - name: var1
      value: value1
  - name: c2
    image: nginx
    ports:
    - containerPort: 80
