apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: r2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rsapp
  template:
    metadata:
      name: rsapp
      labels:
        name: rsapp
    spec:
      containers:
      - name: n1
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: a1
  labels:
    name: rsapp
spec:
  containers:
  - name: apache
    image: tutum/apache-php
    ports:
    - containerPort: 80
