apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
  - name: e1
    image: nginx
    ports: 
    - containerPort: 80
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
  - name: e2
    image: centos
    command: ["/bin/bash"]
    args: ["-c","while true;do X=$[$X+1];echo $X > /usr/share/nginx/html/index.html;sleep 1;done"]
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
  volumes:
  - emptyDir: {} 
    name: data
