apiVersion: v1
kind: Pod
metadata:
  name: d1
spec:
  containers:
  - name: con-1
    image: nginx
    env:
    - name: var1
      value: value1
    resources:
      requests:
        cpu: 1m
        memory: 10M
      limits:
        cpu: 2m
        memory: 50M
